from flask import Flask, Blueprint, render_template, request, session, redirect, url_for, flash, abort
from flask_login import login_user, login_required, logout_user, current_user
from base import db, registration_toggle
from base.decorators import admin_required
from datetime import datetime
from base.lumberjack.views import lumberjack_do
from base.models import User

admin_blueprint = Blueprint('admin', __name__, template_folder='templates/admin')

@admin_blueprint.route('/')
@login_required
@admin_required
def admin():
    # directory of admin functions
    # can this be autogenerated from list of routes, similar to the Toolbox?
    # maybe lookup where the decorator is applied?
    return render_template('admin-home.html')
