from flask_wtf import FlaskForm
from geopy.geocoders import Nominatim
#from base.models import weather model
from wtforms import (StringField,
                     SubmitField,
                     IntegerField,
                     ValidationError,
                     DateField)
from wtforms.validators import DataRequired, EqualTo
from base.lumberjack.views import lumberjack_do
from base.users.views import current_user
from datetime import datetime

class WeatherSubmitForm(FlaskForm):
    city = StringField('City', validators=[DataRequired()])
    # autogenerated
    # gps_coords = StringField('GPS Coordinates', validators=[DataRequired()])
    # see if you can limit dates to the current year.
    date = DateField('Date', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_city(self, field):
        # if city is valid, then it needs to also generate GPS coordinates for the submission
        loc = Nominatim(user_agent="Geopy Library")
        getloc = loc.geocode(field.data)
        try:
            lat = round(float(getloc.latitude), 2)
            long = round(float(getloc.longitude), 2)
            # print(lat, long)
        except AttributeError:
        #     return "Could not convert the entered location name to GPS\n" \
        #            "Please check the spelling and try again"
        # return lat, long
            lumberjack_do(datetime.utcnow(), current_user, "the usual weather", {"type": "Invalid City", 'Submitted City': field.data})
            raise ValidationError('Invalid city name.')